- hosts: kubernetes
  tasks:
  - name: Deploy dream-app
    kubernetes.core.k8s:
      api_version: v1
      namespace: dream-app
      definition:
        kind: Deployment
        metadata:
          labels:
            app: dream-app
          name: dream-app
        spec:
          replicas: 2
          selector:
            matchLabels:
              app: dream-app
          template:
            metadata:
              labels:
                app: dream-app
            spec:
              topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    app: dream-app
              containers:
              - name: dream-app
                image: ademyyazar/dream-app:latest
                ports:
                - containerPort: 8080
                  protocol: TCP
                imagePullSecrets:
                - name: dockercred